apiVersion: v1
kind: ServiceAccount
metadata:
  name: mariadb10618-eks-sa-eksqa
  namespace: eksqa
  labels:
    app: mariadb10618
    tier: database
    code: sql
    country: cl
    language: es
    environment: eksqa
  