apiVersion: v1
kind: Service
metadata:
  name: mariadb10618-svc-eksqa
  namespace: eksqa
  labels:
    app: mariadb10618
    tier: database
    code: sql
    country: cl
    language: es
    environment: eksqa
spec:
  type: NodePort
  ports:
  - port: 30603
    protocol: TCP
    targetPort: 3306
    nodePort: 30603
  selector:
    app: mariadb10618
    tier: database
    code: sql
    country: cl
    language: es
    environment: eksqa
