apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis724-eksdev
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: eksdev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: eksdev/argocd/deploy
    repoURL: https://git-codecommit.us-east-1.amazonaws.com/v1/repos/Redis
    targetRevision: eksdev
  syncPolicy:
    automated:
      selfHeal: true
      prune: true