apiVersion: v1
kind: Service
metadata:
  name: mariadb10618-svc-eksdev
  namespace: eksdev
  labels:
    app: mariadb10618
    tier: database
    code: sql
    country: cl
    language: es
    environment: eksdev
spec:
  type: NodePort
  ports:
  - port: 30602
    protocol: TCP
    targetPort: 3306
    nodePort: 30602
  selector:
    app: mariadb10618
    tier: database
    code: sql
    country: cl
    language: es
    environment: eksdev
