apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql5744-eks-sa-eksdev
  namespace: eksdev
  labels:
    app: mysql5744
    tier: database
    code: sql
    country: cl
    language: es
    environment: eksdev
  