apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql5744-dp-eksdev
  namespace: eksdev
  labels:
    app: mysql5744
    tier: database
    code: sql
    country: cl
    language: es
    environment: eksdev
spec:
  selector:
    matchLabels:
      app: mysql5744
      tier: database
      code: sql
      country: cl
      language: es
      environment: eksdev
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql5744
        tier: database
        code: sql
        country: cl
        language: es
        environment: eksdev
      annotations:
        vault.security.banzaicloud.io/vault-addr: "https://vault-devqa.portalcredex.cl"
        vault.security.banzaicloud.io/vault-tls-secret: "vault-tls"
        vault.security.banzaicloud.io/vault-skip-verify: "true"
        vault.security.banzaicloud.io/vault-role: "mysql5744-eks-role"
        vault.security.banzaicloud.io/vault-env-from-path: "kv/data/administrator_credentials/databases/mysql/5744_eks/dev/connection/credentials_root"
    spec:
      serviceAccountName: mysql5744-eks-sa-eksdev
      imagePullSecrets:
        - name: harbor-registry-secret
      restartPolicy: Always
      containers:
        - name: mysql5744
          image: harbor.portalcredex.cl/databases/mysql5744-credex:0.0.4
          imagePullPolicy: IfNotPresent
          args:
            - "--ignore-db-dir=lost+found"
          ports:
            - containerPort: 3306
          volumeMounts:
          - name: mysql5744-persistent-storage-eksdev
            mountPath: /var/lib/mysql
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: "vault:kv/data/administrator_credentials/databases/mysql/5744_eks/dev/connection/credentials_root#MYSQL_ROOT_PASSWORD"
          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "200m"
      volumes:
        - name: mysql5744-persistent-storage-eksdev
          persistentVolumeClaim:
            claimName: mysql5744-pvc-eksdev
          # startupProbe:
          #   httpGet:
          #     path: /
          #     port: 80
          #   initialDelaySeconds: 5
          #   periodSeconds: 5
          #   failureThreshold: 3
          #   successThreshold: 1
          # readinessProbe:
          #   tcpSocket:
          #     port: 80
          #   timeoutSeconds: 5
          #   periodSeconds: 10
          #   successThreshold: 1