apiVersion: v1
kind: Service
metadata:
  name: mysql5744-svc-eksdev
  namespace: eksdev
  labels:
    app: mysql5744
    tier: database
    code: sql
    country: cl
    language: es
    environment: eksdev
spec:
  type: NodePort
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
    nodePort: 30600
  selector:
    app: mysql5744
    tier: database
    code: sql
    country: cl
    language: es
    environment: eksdev
