apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql5744-pvc-eksdev
  namespace: eksdev
  labels:
    app: mysql5744
    tier: database
    code: sql
    country: cl
    language: es
    environment: eksdev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi