apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis724-sa-eksqa
  namespace: eksqa
  labels:
    app: redis
    tier: database
    code: sql
    country: cl
    language: es
    environment: eksqa
  