apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis724-sa-eksdev
  namespace: eksdev
  labels:
    app: redis724
    tier: database
    code: sql
    country: cl
    language: es
    environment: eksdev
  