# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: redis724-pvc-eksdev
#   namespace: eksdev
#   labels:
#     app: redis724
#     tier: database
#     code: sql
#     country: cl
#     language: es
#     environment: eksdev
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 5Gi