apiVersion: v1
kind: Service
metadata:
  name: mysql5744-svc-eksqa
  namespace: eksqa
  labels:
    app: mysql5744
    tier: database
    code: sql
    country: cl
    language: es
    environment: eksqa
spec:
  type: NodePort
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
    nodePort: 30601
  selector:
    app: mysql5744
    tier: database
    code: sql
    country: cl
    language: es
    environment: eksqa
