apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql5744-pvc-eksqa
  namespace: eksqa
  labels:
    app: mysql5744
    tier: database
    code: sql
    country: cl
    language: es
    environment: eksqa
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi