apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis724-sa-eksprod
  namespace: eksprod
  labels:
    app: redis
    tier: database
    code: sql
    country: cl
    language: es
    environment: eksprod
  