# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: redis-pvc-eksqa
#   namespace: eksqa
#   labels:
#     app: redis
#     tier: database
#     code: sql
#     country: cl
#     language: es
#     environment: eksqa
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 5Gi