apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql5744-eksqa
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: eksqa
    server: https://kubernetes.default.svc
  project: default
  source:
    path: eksqa/argocd/deploy
    repoURL: https://xyz.git
    targetRevision: qa
  syncPolicy:
    automated:
      selfHeal: true
      prune: true